# SRS 6.0 Configuration for HomeGuard-RTC (Phase 1)
# For local testing over WebRTC TCP

listen              1935;
max_connections     1000;
daemon              off;
srs_log_tank        console;

http_api {
    enabled         on;
    listen          1985;
}

http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

stats {
    network         0;
}

rtc_server {
    enabled         on;
    # Use WebRTC over TCP
    protocol        tcp;
    candidate       127.0.0.1;
    tcp {
        enabled     on;
        listen      8000;
    }
}

vhost __defaultVhost__ {
    rtc {
        enabled     on;
        # WHIP / WHEP rely on RTC
        bframe      discard;
    }
}
